### ISSUE TITLE
assert x[4] == "end" AssertionError

### ISSUE THREAD

**Issue by Karimi-81** [mcfrith/genome-rearrangements#1]
Hi there,
I faced the following error when running the script "genome-rearrangements.py" on the .maf file:
assert x[4] == "end" AssertionError
 how can I solve this error? Can it be due to the format structure of .maf file? 
Thanks

**Comment by mcfrith** [comment]
Sorry for the slow response. I guess it's because the alignments are not one-to-one?

**Comment by Karimi-81** [comment]
Thank you for your response. I also think this is due to not being in a one-to-one format. I used "GSAlign"(https://github.com/hsinnan75/GSAlign) to generate maf file between two genomes (with -one parameter). However, I am not sure if it produces a suitable format for the script.  Is there any instruction to generate one-to-one maf file between two large mammalian genomes?
Thanks

**Comment by mcfrith** [comment]
There are suggestions for one-to-one genome alignment near there end of here:
https://gitlab.com/mcfrith/last/-/blob/main/doc/last-cookbook.rst
